name: Integration Test

on: [push, pull_request]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Accuire tools for kind
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true

      # Clone kuberentes goat
      - name: Clone Kubernetes Goat
        run: |
          git clone https://github.com/madhuakula/kubernetes-goat ./kubernetes-goat
      
      # Setup kind cluster
      - name: Setup Kubernetes Goat
        run: |
         cd kubernetes-goat && bash ./kind-setup/setup-kind-cluster-and-goat.sh
      
      - name: Testing Cluster
      - run: |
          kubectl cluster-info
          kubectl get pods -n kube-system