name: Integration Test

on: [push, pull_request]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      # Accuire tools for kind
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          skipClusterCreation: true

      # Clone kuberentes goat
      - name: Clone Kubernetes Goat
        run: |
          git clone https://github.com/madhuakula/kubernetes-goat ./kubernetes-goat
      
      # Setup kind cluster
      - name: Setup Kubernetes Goat
        run: |
         bash goat/kind-setup/setup-kind-cluster-and-goat.sh
