name: Integration Test

on: [push, pull_request]

jobs:
  test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      # Accuire tools for kind
      - uses: engineerd/setup-kind@v0.5.0

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Builds a local kube-hunter docker image
      - name: Build Kube-Hunter Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: kube-hunter:integration

      - run: |
          docker run --network host --rm kube-hunter:integration --interface --log debug --active
        