name: Integration Test

on: [push, pull_request]

jobs:
  test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Builds a local kube-hunter docker image
      - name: Build Kube-Hunter Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: localhost:5000/kube-hunter:integration

      # Run local registry to use with kind
      - name: Run Local Registry
        run: |
          docker run -d -p 5000:5000 registry:2      
      
      - name: Wait For Registry To Load
        run: | 
          sleep 3
      
      # Push kube-hunter image to local registry
      - name: Push kube-hunter image to locally deployed registry
        run: |
          docker push localhost:5000/kube-hunter:integration
      
      - name: Setup The Kind Cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Run Integration Tests
        run: |
          ./integration_tests/run_tests.sh localhost:5000/kube-hunter:integration