name: Integration Test

on: [push, pull_request]

jobs:
  test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      # Accuire tools for kind
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true

      # Clone kuberentes goat
      - name: Clone Kubernetes Goat
        run: |
          git clone https://github.com/madhuakula/kubernetes-goat ./kubernetes-goat
      
      # Setup kind cluster
      - name: Setup Kubernetes Goat
        run: |
         cd kubernetes-goat && bash ./kind-setup/setup-kind-cluster-and-goat.sh && cd ..
      
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Builds a local kube-hunter docker image
      - name: Build Kube-Hunter Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: kube-hunter:integration-${{ github.ref }}

      - run: |
          docker images
        